### ISSUE TITLE
Physical objects not returned in mesh cell_data_dict

### ISSUE THREAD

**Issue by harrymd** [nschloe/pygmsh#378]
In `pygmsh 7.0.0`, meshes returned by `generate_mesh()` do not have physical objects in their `cell_data_dict`. Here is a MWE which raises `KeyError: 'gmsh:physical'` with gmsh version 4.6.0.

```python
import matplotlib.pyplot as plt
import numpy as np
import pygmsh

def main():

    print('pygmsh version: {:}'.format(pygmsh.__version__))
    
    # Define radius of circular domain.
    radius = 1.0

    # Define points of internal square subdomain.
    x0 = -0.4*radius
    x1 = -x0 
    y0 = x0
    y1 = x1
    square_pts = np.array([
                    [x0, y0],
                    [x0, y1],
                    [x1, y1],
                    [x1, y0]])
    n_square_pts = square_pts.shape[0]

    # Set the mesh size.
    mesh_size = radius*0.1

    # Create geometry.
    with pygmsh.geo.Geometry() as geom:

        # Create circular outer boundary.
        circular_boundary = geom.add_circle([0.0, 0.0], radius, mesh_size = mesh_size)

        # Add points that are the vertices of the square.
        pt_list = []
        for i in range(n_square_pts):

            pt = geom.add_point(square_pts[i, :], mesh_size = mesh_size)
            pt_list.append(pt)

        # Add the straight-line segments that form the boundary of the square.
        line_list = []
        for i in range(n_square_pts):

            i0 = i
            i1 = (i + 1) % n_square_pts
            line = geom.add_line(pt_list[i0], pt_list[i1])
            geom.in_surface(line, circular_boundary.plane_surface)
            line_list.append(line)

        # Combine the straight-line segments into a loop.
        line_loop = geom.add_curve_loop(line_list)

        # Add some physical features.
        geom.add_physical(line_loop, label = 'square_outline')
        geom.add_physical(pt_list[0], 'first_point')
        geom.add_physical(line_list[0], 'first_line')

        # Generate the mesh.
        mesh = geom.generate_mesh()

    # This line causes an error.
    print(mesh.cell_data_dict["gmsh:physical"])

    # Plot the results.
    mesh_pts = mesh.points[:, 0:2].T
    mesh_tri = mesh.get_cells_type('triangle')[:, 0:2].T

    fig = plt.figure()
    ax = plt.gca()

    ax.triplot(*mesh_pts, triangles = mesh_tri)

    ax.scatter(*square_pts.T, c = 'r', zorder = 10)

    ax.set_aspect(1.0)

    plt.show()

    return

if __name__ == '__main__':

    main()
```

**Comment by gdmcbain** [comment]
When I run this with on the master branches of pygmsh and meshio, I get
```
AttributeError: module 'meshio.gmsh' has no attribute 'gmsh_to_meshio_type'
```

**Comment by gdmcbain** [comment]
&hellip;but I confirm that with `pip install pygmsh meshio` gives the `KeyError`.

**Comment by gdmcbain** [comment]
It is disappointing that support for physical entities has dropped again (#223).

There was some discussion of a way to work around this in #373 but for the moment the best bet might be `pip install "pygmsh<7"`; except of course that that raises
```
AttributeError: module 'pygmsh' has no attribute 'geo'
```

**Comment by nschloe** [comment]
I'm working on it.

**Comment by nschloe** [comment]
I fixed some things around physical entities in pygmsh as well as meshio (see, e.g., https://github.com/nschloe/pygmsh/issues/373#issuecomment-705039560), and most things are working now. Unfortunately, the above code is not working, and I don't know why. For some reason, `getPhysicalGroups()` at https://github.com/nschloe/pygmsh/blob/master/pygmsh/common/geometry.py#L400 returns `[]`. PRs welcome.

**Comment by nschloe** [comment]
@harrymd I like about your issue that you provided a working example that everyone can use to reproduce the error. You could do even better cutting out all the unnecessary stuff (like mpl), and reducing the geometry further. I'm sure the issue can be reproduced in ~5 lines of code. Still, good job.

**Comment by harrymd** [comment]
@gdmcbain Thanks for the suggested workarounds. I can confirm that l installed `pygmsh` using `pip install pygmsh`. For the time being I will use `pygmsh<7`.

@nschloe Thanks for the encouraging comments. I see now that the MWE is not 'minimal' but I am glad it is helpful. I had a look at `getPhysicalGroups()` (https://gitlab.onelab.info/gmsh/gmsh/-/blob/master/Common/gmsh.cpp#L354) but sadly I am out of my depth with C++, so I don't think I can contribute a PR.

**Comment by beckerrh** [comment]
Hello, Thanks a lot for the recent changes. Unfortunately, I still have problem to retrieve the physical labels. The following example gives me an empty 'mesh.cell_data_dict'.
"
with pygmsh.geo.Geometry() as geom:
    p = geom.add_rectangle(0.0, 1.0, 0.0, 1.0, 0.0, mesh_size=0.1)
    geom.add_physical(p.surface, label="100")
    for i in range(4): geom.add_physical(p.lines[i], label=f"{1000 + i}")
    mesh = geom.generate_mesh()
    print("mesh.cell_data_dict", mesh.cell_data_dict)
"
